name: Bandit Code Scan

on:
  pull_request:
    branches: [ main ]

jobs:
  bandit-action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Bandit Scan
      uses: ./
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        path: "."
        level: "high"
        confidence: "high"
        exit_zero: "true"
